openapi: 3.0.0
info:
  title: Review API
  version: 1.0.0
  description: API for creating reviews for stores

paths:
  /myPage/review/{storeId}:
    post:
      tags:
        - Review
      summary: Create a review for a store
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the store to review
            example: 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 유저 아이디
                  example: 10
                store_id:
                  type: integer
                  description: 가게 아이디
                  example: 3
                body:
                  type: string
                  description: 리뷰 본문
                  example: '음식이 정말 맛있고 분위기도 좋아요'
                score:
                  type: number
                  format: float
                  description: 리뷰 점수
                  example: 4.5
      responses:
        '200':
          description: Review created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: 'success!'
                  data:
                    type: object
                    properties:
                      user_id:
                        type: integer
                        example: 10
                      store_id:
                        type: integer
                        example: 3
                      body:
                        type: string
                        example: '음식이 정말 맛있고 분위기도 좋아요'
                      score:
                        type: number
                        format: float
                        example: 4.5
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
